export const ACTIONS = {
    JOIN: 'join',
    LEAVE: 'leave',
    ADD_PEER: 'add-peer',
    RELAY_ICE: 'relay-ice',
    RELAY_SDP: 'relay-sdp',
    ICE_CANDIDATE: 'ice-candidate',
    SESSION_DESCRIPTION: 'session-description',
    REMOVE_PEER: 'remove-peer',
    MUTE: 'mute',
    UN_MUTE: 'un-mute',
    KICK_USER: 'kick-user',
    MAKE_SPEAKER: 'make-speaker',
    MAKE_LISTENER: 'make-listener',
    REMOVE_ROOM: 'remove-room',
    RAISE_HAND: 'raise-hand',
    LOWER_HAND: 'lower-hand',
    SEND_MSG: 'send-msg',
    RECEIVE_MSG: 'receive-msg',
    SEND_REACTION: 'send-reaction',
    RECEIVE_REACTION: 'receive-reaction',
}